# Generated by Django 3.2 on 2021-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_electroruedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True)),
                ('celular_1', models.CharField(blank=True, max_length=11, null=True)),
                ('celular_2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_lu_vier', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_sab', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_dom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '7. Contacto ElecctroRuedas',
            },
        ),
        migrations.CreateModel(
            name='Contacto_redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('behance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '8. Contácto Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Marca_Xurimotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(help_text='imagenes 20*20', upload_to='marca')),
                ('logo_horizontal', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='marca')),
                ('logo_horizontal_blanco', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='marca')),
                ('logo', models.ImageField(help_text='imagenes 20*20', upload_to='favicon')),
                ('logo_blanco', models.ImageField(help_text='imagenes 20*20', upload_to='favicon')),
            ],
            options={
                'verbose_name_plural': '1. Electroruedas',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '2. Slider',
            },
        ),
    ]
