# Generated by Django 3.2 on 2021-05-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto_electroruedas',
            options={'verbose_name_plural': '7. Contacto Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='marca_xurimotos',
            options={'verbose_name_plural': '1. Marca Xurimotos'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='titulo',
            new_name='titulo_1',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='logo_horizontal',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='logo_horizontal_blanco',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='detalle',
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='logo_gris',
            field=models.ImageField(blank=True, null=True, upload_to='favicon'),
        ),
        migrations.AddField(
            model_name='slider',
            name='titulo_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo_blanco',
            field=models.ImageField(blank=True, null=True, upload_to='marca'),
        ),
    ]
