# Generated by Django 3.2 on 2021-05-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210430_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria_Xurimotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag_1', models.ImageField(blank=True, help_text='imagenes 500*500', null=True, upload_to='media')),
                ('imag_2', models.ImageField(blank=True, help_text='imagenes 500*500', null=True, upload_to='media')),
                ('imag_3', models.ImageField(blank=True, help_text='imagenes 500*500', null=True, upload_to='media')),
                ('imag_4', models.ImageField(blank=True, help_text='imagenes 500*500', null=True, upload_to='media')),
                ('imag_5', models.ImageField(blank=True, help_text='imagenes 500*500', null=True, upload_to='media')),
                ('imag_6', models.ImageField(blank=True, help_text='imagenes 500*500', null=True, upload_to='media')),
                ('imag_7', models.ImageField(blank=True, help_text='imagenes 500*500', null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': '3. Galeria_XuriMotos',
            },
        ),
        migrations.AlterModelOptions(
            name='contacto_electroruedas',
            options={'verbose_name_plural': '4. Contacto Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='contacto_redes',
            options={'verbose_name_plural': '5. Contácto Redes Sociales'},
        ),
    ]
