# Generated by Django 3.2 on 2021-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210430_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagenes 500*900, si se envia en otro tamaño la aplicación cambiará el tamaño automáticamente', null=True, upload_to='slider'),
        ),
    ]
