# Generated by Django 3.2 on 2021-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_slider_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto_electroruedas',
            new_name='Contacto_xurimotos',
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_1',
            field=models.ImageField(blank=True, help_text='Imagen partes moto', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_2',
            field=models.ImageField(blank=True, help_text='Imagen publicidad  horizontal partes', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_3',
            field=models.ImageField(blank=True, help_text='Imagen pie de foto  horizontal', null=True, upload_to='media'),
        ),
    ]
