# Generated by Django 3.2 on 2021-05-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210501_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria_comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(blank=True, help_text='Imagenes de la Comunidad de Xurimoto', null=True, upload_to='galeria')),
            ],
            options={
                'verbose_name_plural': '4. Galeria Comunidad',
            },
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='Imagenes de la Comunidad de Xurimoto', null=True, upload_to='valores')),
                ('quienes_somos', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Valores',
            },
        ),
        migrations.CreateModel(
            name='Xurimotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quienes_somos', models.TextField(blank=True, max_length=100, null=True)),
                ('mision', models.CharField(blank=True, max_length=100, null=True)),
                ('vision', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Xurimotos',
            },
        ),
        migrations.AlterModelOptions(
            name='contacto_redes',
            options={'verbose_name_plural': '8. Contácto Redes Sociales'},
        ),
        migrations.AlterModelOptions(
            name='contacto_xurimotos',
            options={'verbose_name_plural': '7. Contacto Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='galeria_xurimotos',
            options={'verbose_name_plural': '6. Galeria_XuriMotos'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '5. Slider'},
        ),
    ]
