# Generated by Django 3.2 on 2021-05-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210502_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xurimotos',
            options={'verbose_name_plural': '3. Xurimotoss'},
        ),
    ]
