# Generated by Django 3.2 on 2021-05-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_xurimotos_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Xurimotos',
            new_name='Xurimotos_datos',
        ),
    ]
