# Generated by Django 3.2 on 2021-05-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20210502_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa_xurimotos',
            options={'verbose_name_plural': '2. Empresa Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='valores',
            options={'verbose_name_plural': '3. Valores Empresa '},
        ),
        migrations.RemoveField(
            model_name='valores',
            name='quienes_somos',
        ),
        migrations.AddField(
            model_name='valores',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
