# Generated by Django 3.2 on 2021-05-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20210502_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto_xurimotos',
            old_name='celular_2',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='contacto_xurimotos',
            old_name='celular_1',
            new_name='telefono',
        ),
    ]
