# Generated by Django 3.2 on 2021-05-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20210502_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_xurimotos',
            name='imagen_slider',
            field=models.ImageField(blank=True, null=True, upload_to='slider'),
        ),
    ]
