# Generated by Django 3.2 on 2021-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_marca_xurimotos_imagen_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_xurimotos',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='marca'),
        ),
    ]
