# Generated by Django 3.2 on 2021-05-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_marca_xurimotos_imagen_principal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto_redes',
        ),
        migrations.DeleteModel(
            name='Contacto_xurimotos',
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='behance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='horario_dom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='horario_lu_vier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='horario_sab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
