# Generated by Django 3.2 on 2021-05-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20210508_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa_Xurimotos',
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='mision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='quienes_somos',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='vision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
