# Generated by Django 3.2 on 2021-05-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20210508_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='behance',
        ),
    ]
