# Generated by Django 3.2 on 2021-05-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_remove_marca_xurimotos_behance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='mision',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='vision',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
