# Generated by Django 3.2 on 2021-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20210508_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_xurimotos',
            name='logo_vertical',
            field=models.ImageField(blank=True, null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo_gris',
            field=models.ImageField(blank=True, null=True, upload_to='marca'),
        ),
    ]
