# Generated by Django 3.2 on 2021-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_auto_20210508_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_smtp', models.CharField(max_length=100)),
                ('puerto', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('copia', models.EmailField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto_redes',
        ),
    ]
