# Generated by Django 3.2 on 2021-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20210510_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa_xurimotos',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa_xurimotos',
            name='quienes_somos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa_xurimotos',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
