# Generated by Django 3.2 on 2021-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_merge_0023_auto_20210512_1448_0024_auto_20210510_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagenes de la Comunidad de Xurimoto', null=True, upload_to='publicidad')),
            ],
            options={
                'verbose_name_plural': '6. Publicidad ',
            },
        ),
    ]
