# Generated by Django 3.2 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_publicidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicidad',
            new_name='Market',
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='mision',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='quienes_somos',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='vision',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
