# Generated by Django 3.2 on 2021-05-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_auto_20210519_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagenes de la Comunidad de Xurimoto', null=True, upload_to='market'),
        ),
    ]
