# Generated by Django 3.2 on 2021-05-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_alter_market_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_xurimotos',
            name='whatsapp_2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='whatsapp_3',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='whatsapp_4',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='telefono',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
