# Generated by Django 3.2 on 2021-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_auto_20210529_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos_editables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_1', models.CharField(blank=True, help_text='Acceder - Título 1 Centrado parte 1', max_length=100, null=True)),
                ('titulo_2', models.CharField(blank=True, help_text='Acceder - Título 1 Centrado parte 2 en negrita', max_length=100, null=True)),
                ('titulo_3', models.CharField(blank=True, help_text='Acceder - Título 1  Encabezado de ventana emergente - Aún no soy cliente ', max_length=100, null=True)),
                ('titulo_4', models.CharField(blank=True, help_text='Acceder - Título 2  Texto de ventana emergente - Aún no soy cliente ', max_length=100, null=True)),
                ('titulo_5', models.CharField(blank=True, help_text='Pie de Página - Leyenda, frase centrada  empresa', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Títulos Editables ',
            },
        ),
        migrations.AlterModelOptions(
            name='galeria_comunidad',
            options={'verbose_name_plural': '6. Galeria Comunidad'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name_plural': '7. Publicidad '},
        ),
        migrations.AlterField(
            model_name='galeria_comunidad',
            name='imag',
            field=models.ImageField(blank=True, help_text='Empresa - Imagenes de la Comunidad de Xurimoto', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_1',
            field=models.ImageField(blank=True, help_text='Inicio - Imagen partes moto', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_2',
            field=models.ImageField(blank=True, help_text='Empresa - Imagen Principal', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_3',
            field=models.ImageField(blank=True, help_text='Empresa - Imagen Misión', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_4',
            field=models.ImageField(blank=True, help_text='Empresa - Imagen Vision', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_5',
            field=models.ImageField(blank=True, help_text='Empresa - Imagen Pie de página horizontal', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_6',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='galeria_xurimotos',
            name='imag_7',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='celular',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='correo',
            field=models.EmailField(blank=True, help_text='Contacto - Correo electrónico de empresa', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='direccion',
            field=models.CharField(blank=True, help_text='Contacto - Dirección de empresa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='facebook',
            field=models.CharField(blank=True, help_text='Redes Sociales - Facebook - Copiar y pegar  la dirección web de la empresa sin https://www.facebook.com/ ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='favicon',
            field=models.ImageField(blank=True, help_text='50x50 Icono de marca', null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='horario_dom',
            field=models.CharField(blank=True, help_text='Contacto - Horario  Domingo empresa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='horario_lu_vier',
            field=models.CharField(blank=True, help_text='Contacto - Horario de Lunes a Viernes empresa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='horario_sab',
            field=models.CharField(blank=True, help_text='Contacto - Horario  Sabado empresa', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Inicio - Imagen Principal ', null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='imagen_slider',
            field=models.ImageField(blank=True, help_text='Inicio - Imagen Fondo Slider', null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='instagram',
            field=models.CharField(blank=True, help_text='Redes Sociales - Instagram - Copiar y pegar  la dirección web de la empresa sin https://www.instagram.com/ ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Redes Sociales - Linkedin - Copiar y pegar  la dirección web de la empresa sin https://www.linkedin.com/ ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logotipo de  marca', null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo_blanco',
            field=models.ImageField(blank=True, help_text='Logotipo blanco de  marca', null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo_dorado',
            field=models.ImageField(blank=True, help_text='Logotipo dorado de  marca', null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo_gris',
            field=models.ImageField(blank=True, help_text='Logotipo gris de  marca', null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='logo_vertical',
            field=models.ImageField(blank=True, help_text='Logo vertical de marca', null=True, upload_to='marca'),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='mision',
            field=models.TextField(blank=True, help_text='Empresa - Texto misión', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='quienes_somos',
            field=models.TextField(blank=True, help_text='Empresa - Texto quienes somos', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='telefono',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='twitter',
            field=models.CharField(blank=True, help_text='Redes Sociales - Twitter - Copiar y pegar  la dirección web de la empresa sin https://www.twitter.com/ ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='vision',
            field=models.TextField(blank=True, help_text='Empresa - Texto visión', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Contacto - Número Principal de WhatsApp', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp_2',
            field=models.CharField(blank=True, help_text='Contacto - Número 2 de WhatsApp', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp_3',
            field=models.CharField(blank=True, help_text='Contacto - Número 3 de WhatsApp', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp_4',
            field=models.CharField(blank=True, help_text='Contacto - Número 4 de WhatsApp', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='youtube',
            field=models.CharField(blank=True, help_text='Redes Sociales - Youtube - Copiar y pegar  la dirección web de la empresa sin https://www.youtube.com/ ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Inicio - Slider  Imagenes 500*900, si se envia en otro tamaño la aplicación cambiará el tamaño automáticamente', null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titulo_1',
            field=models.CharField(blank=True, help_text='Inicio - Slider  Titulo 1 Grande color Negro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titulo_2',
            field=models.CharField(blank=True, help_text='Inicio - Slider  Titulo 2 Pequeño Color Rojo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valores',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Empresa - Imagen de Valor', null=True, upload_to='valores'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='valor',
            field=models.CharField(blank=True, help_text='Empresa - Escribir un Valor', max_length=100, null=True),
        ),
    ]
