# Generated by Django 3.2 on 2021-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_auto_20210530_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulos_editables',
            name='titulo_3',
            field=models.CharField(blank=True, help_text='Acceder - Título 1  Encabezado de ventana emergente - Aún no soy cliente ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='titulos_editables',
            name='titulo_4',
            field=models.CharField(blank=True, help_text='Acceder - Título 2  Texto de ventana emergente - Aún no soy cliente ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='titulos_editables',
            name='titulo_5',
            field=models.CharField(blank=True, help_text='Pie de Página - Leyenda, frase centrada  empresa', max_length=200, null=True),
        ),
    ]
