# Generated by Django 3.2 on 2021-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_auto_20210530_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria_comunidad',
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name_plural': '6. Publicidad '},
        ),
        migrations.RemoveField(
            model_name='galeria_xurimotos',
            name='imag_6',
        ),
        migrations.RemoveField(
            model_name='galeria_xurimotos',
            name='imag_7',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='logo_blanco',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='logo_dorado',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='logo_gris',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='logo_vertical',
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='logo_pie_pag',
            field=models.ImageField(blank=True, help_text='Logotipo pie de  página marca', null=True, upload_to='marca'),
        ),
    ]
