# Generated by Django 3.2 on 2022-03-28 05:23

from django.db import migrations, models
import xurimotos.snippers


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_auto_20210531_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacados_Xurimotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_titulo_01', models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True)),
                ('dest_sub_titulo_01', models.CharField(blank=True, help_text='Subtitulo - Secc-Productos P3', max_length=100, null=True)),
                ('dest_titulo_02', models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True)),
                ('dest_link_02', models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True)),
                ('dest_imagen_02', models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria')),
                ('dest_titulo_03', models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True)),
                ('dest_link_03', models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True)),
                ('dest_imagen_03', models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria')),
                ('dest_titulo_04', models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True)),
                ('dest_link_04', models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True)),
                ('dest_imagen_04', models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria')),
                ('dest_titulo_05', models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True)),
                ('dest_link_05', models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True)),
                ('dest_imagen_05', models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria')),
                ('dest_titulo_06', models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True)),
                ('dest_link_06', models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True)),
                ('dest_imagen_06', models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria')),
            ],
            options={
                'verbose_name_plural': '3. Destacados Xurimotos',
            },
        ),
        migrations.CreateModel(
            name='Editable_Xurimotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_1', models.CharField(blank=True, help_text='Subtítulo 1 - Secc-Inicio P1', max_length=100, null=True)),
                ('titulo_1', models.CharField(blank=True, help_text='Título 1 - Secc-Inicio P1', max_length=100, null=True)),
                ('detalle_1', models.CharField(blank=True, help_text='Detalle 1 - Secc-Inicio P1', max_length=100, null=True)),
                ('img_1', models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Imagen 1', null=True, upload_to='galeria')),
                ('sub_2', models.CharField(blank=True, help_text='Subtítulo 2 - Secc-Inicio P2 ', max_length=100, null=True)),
                ('titulo_2', models.CharField(blank=True, help_text='Título 2 - Secc-Inicio P2', max_length=100, null=True)),
                ('detalle_2', models.CharField(blank=True, help_text='Detalle 2 - Secc-Inicio P2', max_length=100, null=True)),
                ('sub_3', models.CharField(blank=True, help_text='Subtítulo 3 - Secc-Inicio P3', max_length=100, null=True)),
                ('titulo_3', models.CharField(blank=True, help_text='Título 3 - Secc-Inicio P3', max_length=100, null=True)),
                ('detalle_3', models.CharField(blank=True, help_text='Detalle 3 - Secc-Inicio P3', max_length=100, null=True)),
                ('video_link_1', models.CharField(blank=True, help_text='Link video Youtube - Secc-Inicio p3 Video link 1', max_length=100, null=True)),
                ('banner_img', models.ImageField(blank=True, help_text='1140x344 - Secc-Producto P3', null=True, upload_to='galeria')),
                ('mision_img', models.ImageField(blank=True, help_text='613x526 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria')),
                ('mision_sub', models.CharField(blank=True, help_text='Subtítulo 1 - Secc-Empresa P1', max_length=100, null=True)),
                ('mision_titulo', models.CharField(blank=True, help_text='Título 1 - Secc-Empresa P1', max_length=100, null=True)),
                ('mision_detalle', models.CharField(blank=True, help_text='Detalle 1 - Secc-Empresa P1', max_length=100, null=True)),
                ('vision_img', models.ImageField(blank=True, help_text='613x526 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria')),
                ('vision_sub', models.CharField(blank=True, help_text='Subtítulo 1 - Secc-Empresa P1', max_length=100, null=True)),
                ('vision_titulo', models.CharField(blank=True, help_text='Título 1 - Secc-Empresa P1', max_length=100, null=True)),
                ('vision_detalle', models.CharField(blank=True, help_text='Detalle 1 - Secc-Empresa P1', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Editable Xurimotos',
            },
        ),
        migrations.CreateModel(
            name='Slider_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='Inicio - Slider 2  Imagenes 706*246, si se envia en otro tamaño la aplicación cambiará el tamaño automáticamente', null=True, upload_to='slider')),
            ],
            options={
                'verbose_name_plural': '4. Slider_2',
            },
            bases=(models.Model, xurimotos.snippers.ResizeImageMixin),
        ),
        migrations.DeleteModel(
            name='Galeria_Xurimotos',
        ),
        migrations.DeleteModel(
            name='Titulos_editables',
        ),
        migrations.DeleteModel(
            name='Valores',
        ),
    ]
