# Generated by Django 3.2 on 2022-03-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_auto_20220328_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='titulo_1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='titulo_2',
        ),
        migrations.AddField(
            model_name='slider_2',
            name='color_hexadecimal',
            field=models.CharField(blank=True, help_text='Color variante', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='detalle_1',
            field=models.CharField(blank=True, help_text='Detalle 1 - Secc-Inicio P1', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='detalle_2',
            field=models.CharField(blank=True, help_text='Detalle 2 - Secc-Inicio P2', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='detalle_3',
            field=models.CharField(blank=True, help_text='Detalle 3 - Secc-Inicio P3', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='mision_detalle',
            field=models.CharField(blank=True, help_text='Detalle 1 - Secc-Empresa P1', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='vision_detalle',
            field=models.CharField(blank=True, help_text='Detalle 1 - Secc-Empresa P1', max_length=500, null=True),
        ),
    ]
