# Generated by Django 3.2 on 2022-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_auto_20220328_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editable_xurimotos',
            old_name='img_1',
            new_name='img_1_a',
        ),
        migrations.RenameField(
            model_name='editable_xurimotos',
            old_name='mision_img',
            new_name='mision_img_1',
        ),
        migrations.RenameField(
            model_name='editable_xurimotos',
            old_name='vision_img',
            new_name='mision_img_2',
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_1_b',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_1_c',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='vision_img_1',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='vision_img_2',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
    ]
