# Generated by Django 3.2 on 2022-03-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_auto_20220328_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_2',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Imagen 1', null=True, upload_to='galeria'),
        ),
    ]
