# Generated by Django 3.2 on 2022-03-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0036_editable_xurimotos_img_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidores_Xurimotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, help_text='Ingresar ubicación del local', max_length=100, null=True)),
                ('local', models.CharField(blank=True, help_text='Ingresar nombre del local', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Ingresar dirección del local', max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Ingresar correo de local', max_length=254, null=True)),
                ('horario', models.CharField(blank=True, help_text='Ingresar horario de atención del local', max_length=500, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Ingresar foto del local', null=True, upload_to='galeria')),
                ('contacto', models.CharField(blank=True, help_text='Ingresar contacto del local', max_length=150, null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ingresar contacto del local', max_length=700, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Distribuidores Xurimotos',
            },
        ),
    ]
