# Generated by Django 3.2 on 2022-03-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0038_auto_20220328_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrusel_producto',
            name='color_hexadecimal',
        ),
    ]
