# Generated by Django 3.2 on 2022-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0039_remove_carrusel_producto_color_hexadecimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_xurimotos',
            name='mapa',
            field=models.TextField(blank=True, help_text='Link de Mapa Xuri Moto', null=True),
        ),
    ]
