# Generated by Django 3.2 on 2022-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0040_marca_xurimotos_mapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(help_text='imagen de 1280*500', upload_to='blog/')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('articulo', models.TextField(blank=True, max_length=10000, null=True)),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20)),
                ('tipo_imagen', models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='blog/')),
                ('tipo_video_link', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Blogs',
            },
        ),
    ]
