# Generated by Django 3.2 on 2022-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0041_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_atencion',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Atención al cliente', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_despacho',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Despacho', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_ventas',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Ventas', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='telef_atencion',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Atención al cliente', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='telef_despacho',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Despacho', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='telef_ventas',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Ventas', max_length=13, null=True),
        ),
    ]
