# Generated by Django 3.2 on 2022-03-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0042_auto_20220328_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='celular',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='celular_atencion',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Atención al cliente', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='celular_despacho',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Despacho', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='celular_ventas',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Ventas', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='telef_atencion',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Atención al cliente', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='telef_despacho',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Despacho', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='telef_ventas',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Ventas', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='telefono',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Contacto - Número Principal de WhatsApp', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp_2',
            field=models.CharField(blank=True, help_text='Contacto - Número 2 de WhatsApp', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp_3',
            field=models.CharField(blank=True, help_text='Contacto - Número 3 de WhatsApp', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marca_xurimotos',
            name='whatsapp_4',
            field=models.CharField(blank=True, help_text='Contacto - Número 4 de WhatsApp', max_length=15, null=True),
        ),
    ]
