# Generated by Django 3.2 on 2022-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0043_auto_20220328_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_centro_ayuda',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Centro de Ayuda', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_marketing_ventas',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Marketing & Ventas', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_soporte_tec',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Soporte Técnico', max_length=15, null=True),
        ),
    ]
