# Generated by Django 3.2 on 2022-03-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0045_editable_xurimotos_slider_1_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_imagen_07',
            field=models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_imagen_08',
            field=models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_imagen_09',
            field=models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_imagen_10',
            field=models.ImageField(blank=True, help_text='325x275 - Secc-Productos P3 Imagen', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_link_07',
            field=models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_link_08',
            field=models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_link_09',
            field=models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_link_10',
            field=models.CharField(blank=True, help_text='Link  - Secc-Productos P3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_titulo_07',
            field=models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_titulo_08',
            field=models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_titulo_09',
            field=models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destacados_xurimotos',
            name='dest_titulo_10',
            field=models.CharField(blank=True, help_text='Título - Secc-Productos P3', max_length=100, null=True),
        ),
    ]
