# Generated by Django 3.2 on 2022-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0046_auto_20220330_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='celular_atencion',
            new_name='celular_atencion_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='celular_centro_ayuda',
            new_name='celular_centro_ayuda_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='celular_despacho',
            new_name='celular_despacho_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='celular_marketing_ventas',
            new_name='celular_marketing_ventas_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='celular_soporte_tec',
            new_name='celular_soporte_tec_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='celular_ventas',
            new_name='celular_ventas_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='telef_atencion',
            new_name='telef_atencion_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='telef_despacho',
            new_name='telef_despacho_1',
        ),
        migrations.RenameField(
            model_name='marca_xurimotos',
            old_name='telef_ventas',
            new_name='telef_ventas_1',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='whatsapp_2',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='whatsapp_3',
        ),
        migrations.RemoveField(
            model_name='marca_xurimotos',
            name='whatsapp_4',
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_atencion_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Atención al cliente', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_centro_ayuda_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Centro de Ayuda', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_despacho_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Despacho', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_marketing_ventas_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Marketing & Ventas', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_soporte_tec_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Soporte Técnico', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='celular_ventas_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Celular Ventas', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='telef_atencion_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Atención al cliente', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='telef_despacho_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Despacho', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='telef_ventas_2',
            field=models.CharField(blank=True, help_text='Contacto - Número Teléfono Ventas', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='marca_xurimotos',
            name='tiktok',
            field=models.CharField(blank=True, help_text='Redes Sociales - Tiktok - Copiar y pegar  la dirección web de la empresa sin https://www.tiktok.com/ ', max_length=100, null=True),
        ),
    ]
