# Generated by Django 3.2 on 2022-04-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0047_auto_20220405_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': '9. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='carrusel_producto',
            options={'verbose_name_plural': '5. Carrusel_producto'},
        ),
        migrations.AlterModelOptions(
            name='destacados_xurimotos',
            options={'verbose_name_plural': '4. Destacados Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='distribuidores_xurimotos',
            options={'verbose_name_plural': '7. Distribuidores Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name_plural': '8. Publicidad '},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '3. Slider'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Inicio - Slider  Imagenes 500*900', null=True, upload_to='slider'),
        ),
        migrations.CreateModel(
            name='Galeria_carrusel_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_1', models.ImageField(blank=True, help_text='Producto - Carrusel Producto  Imagenes 706*246, si se envia en otro tamaño la aplicación cambiará el tamaño automáticamente', null=True, upload_to='carrusel')),
                ('imagen_2', models.ImageField(blank=True, help_text='Producto - Carrusel Producto  Imagenes 706*246, si se envia en otro tamaño la aplicación cambiará el tamaño automáticamente', null=True, upload_to='carrusel')),
                ('imagen_3', models.ImageField(blank=True, help_text='Producto - Carrusel Producto Imagenes 706*246, si se envia en otro tamaño la aplicación cambiará el tamaño automáticamente', null=True, upload_to='carrusel')),
                ('producto_carrusel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.carrusel_producto')),
            ],
            options={
                'verbose_name_plural': '6. Galeria Carrusel_producto',
            },
        ),
    ]
