# Generated by Django 3.2 on 2022-04-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0048_auto_20220405_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrusel_producto',
            name='imagen_2',
        ),
        migrations.RemoveField(
            model_name='carrusel_producto',
            name='imagen_3',
        ),
    ]
