# Generated by Django 3.2 on 2022-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0049_auto_20220405_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable_xurimotos',
            name='vision_img_dere',
            field=models.ImageField(blank=True, help_text='350x250 - Secc-Empresa P1 Imagen  derecha misión', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='vision_img_izq',
            field=models.ImageField(blank=True, help_text='250x350 - Secc-Empresa P1 Imagen izquierda misión', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_1_a',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Slider Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_1_b',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Slider Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_1_c',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Slider Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_2',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P3 Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='vision_img_1',
            field=models.ImageField(blank=True, help_text='400x250 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='vision_img_2',
            field=models.ImageField(blank=True, help_text='400x250 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
    ]
