# Generated by Django 3.2 on 2022-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0051_auto_20220407_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '10. Suscripción Email',
            },
        ),
    ]
