# Generated by Django 3.2 on 2022-04-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0052_suscripcion_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion_Email',
        ),
    ]
