# Generated by Django 3.2 on 2022-04-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0053_delete_suscripcion_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='imagen',
        ),
    ]
