# Generated by Django 3.2 on 2022-04-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0054_remove_blogs_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20)),
                ('tipo_imagen', models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='slider/')),
                ('tipo_video', models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='slider/')),
            ],
            options={
                'verbose_name_plural': '3. Slider fondo Video',
            },
        ),
        migrations.AddField(
            model_name='slider',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
