# Generated by Django 3.2 on 2022-04-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0056_suscripcion_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_galeria_carrusel',
            name='imagen_1',
            field=models.ImageField(blank=True, help_text='Producto - Carrusel Producto  Imagenes 400*400', null=True, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_galeria_carrusel',
            name='imagen_2',
            field=models.ImageField(blank=True, help_text='Producto - Carrusel Producto  Imagenes 400*400', null=True, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_galeria_carrusel',
            name='imagen_3',
            field=models.ImageField(blank=True, help_text='Producto - Carrusel Producto  Imagenes 400*400', null=True, upload_to='carrusel'),
        ),
    ]
