# Generated by Django 3.2 on 2022-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0057_auto_20220408_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_fondo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
