# Generated by Django 3.2 on 2022-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0058_slider_fondo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_fondo',
            field=models.ImageField(blank=True, help_text='1920x420 - Secc-Inicio P3 Fondo Video', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_1_a',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P1 Slider Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_1_b',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P1 Slider Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_1_c',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P1 Slider Imagen 1', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='img_2',
            field=models.ImageField(blank=True, help_text='613x526 - Secc-Inicio P2 Imagen 1', null=True, upload_to='galeria'),
        ),
    ]
