# Generated by Django 3.2 on 2022-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0059_auto_20220409_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tipo_imagen',
            field=models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='distribuidores_xurimotos',
            name='imagen',
            field=models.ImageField(blank=True, help_text='410x300 Ingresar foto del local', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='banner_img',
            field=models.ImageField(blank=True, help_text='1350x390 - Secc-Producto P3', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='mision_img_1',
            field=models.ImageField(blank=True, help_text='660x840 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='mision_img_2',
            field=models.ImageField(blank=True, help_text='660x840 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='vision_img_1',
            field=models.ImageField(blank=True, help_text='455x310- Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='vision_img_2',
            field=models.ImageField(blank=True, help_text='455x310 - Secc-Empresa P1 Imagen misión', null=True, upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='producto_carrusel',
            name='imagen_1',
            field=models.ImageField(blank=True, help_text='368X313 Producto - Carrusel Producto ', null=True, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_galeria_carrusel',
            name='imagen_1',
            field=models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_galeria_carrusel',
            name='imagen_2',
            field=models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_galeria_carrusel',
            name='imagen_3',
            field=models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='slider_fondo',
            name='tipo_imagen',
            field=models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='slider_fondo',
            name='tipo_video',
            field=models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='slider'),
        ),
    ]
