# Generated by Django 3.2 on 2022-04-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0060_auto_20220409_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destacados_xurimotos',
            options={'verbose_name_plural': '5. Destacados Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='distribuidores_xurimotos',
            options={'verbose_name_plural': '8. Distribuidores Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='producto_carrusel',
            options={'verbose_name_plural': '6. Producto Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='producto_galeria_carrusel',
            options={'verbose_name_plural': '7. Galeria Producto Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '4. Slider Prodcutos'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion_email',
            options={'verbose_name_plural': '9.1. Suscripción Email'},
        ),
    ]
