# Generated by Django 3.2 on 2022-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0061_auto_20220410_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='color_ing_1',
            field=models.CharField(blank=True, help_text='Código color - Secc-Productos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='color_ing_2',
            field=models.CharField(blank=True, help_text='Código color - Secc-Productos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='color_ing_3',
            field=models.CharField(blank=True, help_text='Código color - Secc-Productos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='color_ing_4',
            field=models.CharField(blank=True, help_text='Código color - Secc-Productos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='color_ing_5',
            field=models.CharField(blank=True, help_text='Código color - Secc-Productos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='color_ing_6',
            field=models.CharField(blank=True, help_text='Código color - Secc-Productos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='imagen_4',
            field=models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel'),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='imagen_5',
            field=models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel'),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='imagen_6',
            field=models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel'),
        ),
    ]
