# Generated by Django 3.2 on 2022-04-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0063_color_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='color_ing_1',
        ),
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='color_ing_2',
        ),
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='color_ing_3',
        ),
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='color_ing_4',
        ),
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='color_ing_5',
        ),
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='color_ing_6',
        ),
    ]
