# Generated by Django 3.2 on 2022-04-11 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0064_auto_20220411_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='color_ing_1',
            field=models.ForeignKey(blank=True, help_text='Color para  Producto - Carrusel', null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.color_productos'),
        ),
    ]
