# Generated by Django 3.2 on 2022-04-11 18:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0065_producto_galeria_carrusel_color_ing_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='color_ing_1',
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='codigoColor',
            field=colorfield.fields.ColorField(default='#fffff', image_field=None, max_length=18, samples=None),
        ),
    ]
