# Generated by Django 3.2 on 2022-04-11 18:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0066_auto_20220411_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color_Productos',
        ),
        migrations.RenameField(
            model_name='producto_galeria_carrusel',
            old_name='codigoColor',
            new_name='codigo_color_imag_1',
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='codigo_color_imag_2',
            field=colorfield.fields.ColorField(default='#fffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='codigo_color_imag_3',
            field=colorfield.fields.ColorField(default='#fffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='codigo_color_imag_4',
            field=colorfield.fields.ColorField(default='#fffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='codigo_color_imag_5',
            field=colorfield.fields.ColorField(default='#fffff', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='producto_galeria_carrusel',
            name='codigo_color_imag_6',
            field=colorfield.fields.ColorField(default='#fffff', image_field=None, max_length=18, samples=None),
        ),
    ]
