# Generated by Django 3.2 on 2022-04-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0069_auto_20220411_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='codigo_color_imag_6',
        ),
        migrations.RemoveField(
            model_name='producto_galeria_carrusel',
            name='imagen_6',
        ),
    ]
