# Generated by Django 3.2 on 2022-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0071_auto_20220411_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editable_xurimotos',
            name='video_link_1',
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='video',
            field=models.FileField(blank=True, help_text='Link video Youtube - Secc-Inicio p3 Video link 1', null=True, upload_to='galeria'),
        ),
    ]
