# Generated by Django 3.2 on 2022-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0072_auto_20220412_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='video',
            field=models.FileField(blank=True, help_text='Video- Secc-Inicio p3 Video', null=True, upload_to='galeria'),
        ),
    ]
