# Generated by Django 3.2 on 2022-04-12 23:27

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0075_auto_20220412_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_galeria_carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_1', models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel')),
                ('codigo_color_imag_1', colorfield.fields.ColorField(default='FFFFFF', image_field=None, max_length=18, samples=None)),
                ('imagen_2', models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel')),
                ('codigo_color_imag_2', colorfield.fields.ColorField(default='FFFFFF', image_field=None, max_length=18, samples=None)),
                ('imagen_3', models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel')),
                ('codigo_color_imag_3', colorfield.fields.ColorField(default='FFFFFF', image_field=None, max_length=18, samples=None)),
                ('imagen_4', models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel')),
                ('codigo_color_imag_4', colorfield.fields.ColorField(default='FFFFFF', image_field=None, max_length=18, samples=None)),
                ('imagen_5', models.ImageField(blank=True, help_text='368X313 Producto - Carrusel', null=True, upload_to='carrusel')),
                ('codigo_color_imag_5', colorfield.fields.ColorField(default='FFFFFF', image_field=None, max_length=18, samples=None)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.producto_carrusel')),
            ],
            options={
                'verbose_name_plural': '7. Galeria Producto Carrusel',
            },
        ),
    ]
