# Generated by Django 3.2 on 2022-04-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0076_producto_galeria_carrusel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Producto_galeria_carrusel',
        ),
    ]
