# Generated by Django 3.2 on 2022-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0077_auto_20220412_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editable_xurimotos',
            name='img_fondo',
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_fondo_vide_horiz',
            field=models.ImageField(blank=True, help_text='1920x420 - Secc-Inicio P3 Imagen Fondo Horizontal  Video', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_fondo_vide_verti',
            field=models.ImageField(blank=True, help_text='1920x420 - Secc-Inicio P3 Imagen Fondo Vertical  Video', null=True, upload_to='galeria'),
        ),
    ]
