# Generated by Django 3.2 on 2022-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0079_auto_20220414_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editable_xurimotos',
            name='vision_img_dere',
        ),
        migrations.RemoveField(
            model_name='editable_xurimotos',
            name='vision_img_izq',
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_fondo_vide_horiz',
            field=models.FileField(blank=True, help_text='Video- Secc-Inicio p3 Imagen fondo horizontal Video', null=True, upload_to='galeria'),
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='img_fondo_vide_verti',
            field=models.FileField(blank=True, help_text='Video- Secc-Inicio p3 Imagen fondo vertical Video', null=True, upload_to='galeria'),
        ),
    ]
