# Generated by Django 3.2 on 2022-04-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0080_auto_20220414_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_carrusel',
            old_name='estado',
            new_name='activo',
        ),
    ]
