# Generated by Django 3.2 on 2022-04-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0081_rename_estado_producto_carrusel_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Envio_Email',
        ),
    ]
