# Generated by Django 3.2 on 2022-04-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0082_delete_envio_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('imagen_banner', models.ImageField(blank=True, help_text='1350x390 - Secc-Producto P3', null=True, upload_to='banner')),
            ],
            options={
                'verbose_name_plural': '4. Slider Prodcutos',
            },
        ),
        migrations.RemoveField(
            model_name='editable_xurimotos',
            name='banner_img',
        ),
    ]
