# Generated by Django 3.2 on 2022-04-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0083_auto_20220421_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='activo',
        ),
    ]
