# Generated by Django 3.2 on 2022-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0085_auto_20220421_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Destacados_Xurimotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_titulo_01', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_01', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_02', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_02', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_03', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_03', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_04', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_04', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_05', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_05', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_06', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_06', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_07', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_07', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_08', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_08', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_09', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_09', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_titulo_10', models.CharField(blank=True, help_text='Título - Secc-Productos Menú destacados P3', max_length=100, null=True)),
                ('dest_link_titulo_10', models.CharField(blank=True, help_text='Link - Secc-Productos Menú destacados P3', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Menú Destacados Xurimotos',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '4. Banner'},
        ),
        migrations.AlterModelOptions(
            name='destacados_xurimotos',
            options={'verbose_name_plural': '6. Destacados Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='producto_carrusel',
            options={'verbose_name_plural': '7. Producto Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '3. Slider Prodcutos'},
        ),
    ]
