# Generated by Django 3.2 on 2022-04-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0086_auto_20220421_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destacados_xurimotos',
            old_name='dest_imagen_06',
            new_name='dest_imagen_01',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_imagen_07',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_imagen_08',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_imagen_09',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_imagen_10',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_link_06',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_link_07',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_link_08',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_link_09',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_link_10',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_titulo_06',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_titulo_07',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_titulo_08',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_titulo_09',
        ),
        migrations.RemoveField(
            model_name='destacados_xurimotos',
            name='dest_titulo_10',
        ),
    ]
