# Generated by Django 3.2 on 2022-04-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0087_auto_20220421_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '5. Banner'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': '9.1. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='destacados_xurimotos',
            options={'verbose_name_plural': '7. Destacados Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='distribuidores_xurimotos',
            options={'verbose_name_plural': '9. Distribuidores Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='menu_destacados_xurimotos',
            options={'verbose_name_plural': '6. Menú Destacados Xurimotos'},
        ),
        migrations.AlterModelOptions(
            name='producto_carrusel',
            options={'verbose_name_plural': '8. Producto Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '4. Slider Prodcutos'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion_email',
            options={'verbose_name_plural': '9.2. Suscripción Email'},
        ),
    ]
