# Generated by Django 3.2 on 2022-04-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0088_auto_20220421_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_01',
            new_name='menu_dest_titulo_01',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_02',
            new_name='menu_dest_titulo_02',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_03',
            new_name='menu_dest_titulo_03',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_04',
            new_name='menu_dest_titulo_04',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_05',
            new_name='menu_dest_titulo_05',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_06',
            new_name='menu_dest_titulo_06',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_07',
            new_name='menu_dest_titulo_07',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_08',
            new_name='menu_dest_titulo_08',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_09',
            new_name='menu_dest_titulo_09',
        ),
        migrations.RenameField(
            model_name='menu_destacados_xurimotos',
            old_name='dest_titulo_10',
            new_name='menu_dest_titulo_10',
        ),
    ]
