# Generated by Django 3.2 on 2022-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0092_auto_20220422_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tipo_archivo',
            field=models.CharField(choices=[('vacio', 'vacio'), ('imagen', 'imagen'), ('video', 'video'), ('youtube', 'youtube'), ('galeria', 'galeria')], default='vacio', max_length=20),
        ),
    ]
