# Generated by Django 3.2 on 2022-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0093_alter_blogs_tipo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable_xurimotos',
            name='titulo_codigo_color_amarillo',
            field=models.CharField(blank=True, help_text='Código de color para títulos amarillos en fondos claros', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='editable_xurimotos',
            name='titulo_codigo_color_negros',
            field=models.CharField(blank=True, help_text='Código de color para títulos amarillos en fondos claros', max_length=6, null=True),
        ),
    ]
