# Generated by Django 3.2 on 2022-04-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0094_auto_20220423_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='titulo_codigo_color_amarillo',
            field=models.CharField(blank=True, help_text='Código de color para títulos amarillos en fondos claros', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='editable_xurimotos',
            name='titulo_codigo_color_negros',
            field=models.CharField(blank=True, help_text='Código de color para títulos amarillos en fondos claros', max_length=7, null=True),
        ),
    ]
