# Generated by Django 3.2 on 2022-04-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0095_auto_20220423_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editable_xurimotos',
            old_name='titulo_codigo_color_negros',
            new_name='titulo_codigo_color_negro',
        ),
    ]
