# Generated by Django 3.2 on 2022-04-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0096_rename_titulo_codigo_color_negros_editable_xurimotos_titulo_codigo_color_negro'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable_xurimotos',
            name='parrafo_codigo_color_negro',
            field=models.CharField(blank=True, help_text='Código de color para párrafos negros en fondos claros', max_length=7, null=True),
        ),
    ]
