# Generated by Django 3.2 on 2022-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0097_editable_xurimotos_parrafo_codigo_color_negro'),
    ]

    operations = [
        migrations.AddField(
            model_name='editable_xurimotos',
            name='codigo_color_RGBA_sombreado',
            field=models.CharField(blank=True, help_text='Código de color para sombreado de productos', max_length=20, null=True),
        ),
    ]
