# Generated by Django 3.2 on 2021-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(max_length=10)),
                ('unidades_por_caja', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descuento', models.IntegerField(default=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
