# Generated by Django 3.2 on 2021-05-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='unidades_por_caja',
            field=models.CharField(max_length=50),
        ),
    ]
