# Generated by Django 3.2 on 2021-05-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_catalogo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='url',
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='producto'),
        ),
    ]
