# Generated by Django 3.2 on 2021-05-01 21:14

from django.db import migrations, models
import django.db.models.deletion
import xurimotos.snippers


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20210501_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='', verbose_name='producto/galeria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.catalogo')),
            ],
            bases=(models.Model, xurimotos.snippers.ResizeImageMixin),
        ),
    ]
