# Generated by Django 3.2 on 2021-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_auto_20210503_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='icono'),
        ),
    ]
