# Generated by Django 3.2 on 2021-05-05 22:43

from django.db import migrations, models
import xurimotos.snippers


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_categoria_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marcas')),
            ],
            bases=(models.Model, xurimotos.snippers.ResizeImageMixin),
        ),
    ]
