# Generated by Django 3.2 on 2021-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_marcas'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
