# Generated by Django 3.2 on 2021-05-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_catalogo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='aux',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
