# Generated by Django 3.2 on 2021-05-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_catalogo_aux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='foto',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='producto'),
        ),
    ]
