# Generated by Django 3.2 on 2021-05-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0012_detallepedido_pedidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'verbose_name_plural': '3. Catalogo de Productos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': '1. Categorias'},
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name_plural': '2. Marcas'},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name_plural': '4. Pedidos'},
        ),
    ]
