# Generated by Django 3.2 on 2021-05-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_auto_20210510_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='producto/galeria'),
        ),
    ]
