# Generated by Django 3.2 on 2022-03-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0016_alter_catalogo_precio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='info_tecnica',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
