# Generated by Django 3.2 on 2022-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0017_catalogo_info_tecnica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name_plural': '4. Galeria'},
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='info_tecnica',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
    ]
