# Generated by Django 3.2 on 2022-04-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0018_auto_20220410_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
