# Generated by Django 3.2 on 2022-04-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0019_auto_20220413_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='precio_final',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='unidades_por_caja',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='detalle',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='info_tecnica',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
