# Generated by Django 3.2 on 2022-04-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0020_auto_20220414_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='color',
        ),
    ]
