# Generated by Django 3.2 on 2022-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0021_remove_catalogo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='nombre_producto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
