# Generated by Django 3.2 on 2022-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0025_auto_20220414_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='detalle',
            field=models.TextField(),
        ),
    ]
