# Generated by Django 3.2 on 2022-04-15 15:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0026_alter_catalogo_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='codigo_color_imag_1',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
