# Generated by Django 3.2 on 2022-04-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0027_galeria_codigo_color_imag_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='codigo_color_imag_1',
        ),
    ]
