# Generated by Django 3.2 on 2022-04-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0028_remove_galeria_codigo_color_imag_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'verbose_name_plural': '2. Catalogo de Productos'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name_plural': '3. Galeria de Productos'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
    ]
